// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGymSystem.Context;

#nullable disable

namespace MyGymSystem.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20251018191346_Models")]
    partial class Models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyGymSystem.Models.Aboutuspage", b =>
                {
                    b.Property<long>("Aboutuspageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Aboutuspageid"));

                    b.Property<string>("Imagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Lastupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Missionstatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teamdescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Updatedbyadminid")
                        .HasColumnType("bigint");

                    b.Property<string>("Visionstatement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Aboutuspageid");

                    b.HasIndex("Updatedbyadminid");

                    b.ToTable("Aboutuspages");
                });

            modelBuilder.Entity("MyGymSystem.Models.Admin", b =>
                {
                    b.Property<long>("Adminid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Adminid"));

                    b.Property<DateTime?>("Dateofbirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Adminid");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MyGymSystem.Models.Contactuspage", b =>
                {
                    b.Property<long>("Contactuspageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Contactuspageid"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Lastupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mapembedcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picpath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Updatedbyadminid")
                        .HasColumnType("bigint");

                    b.HasKey("Contactuspageid");

                    b.HasIndex("Updatedbyadminid");

                    b.ToTable("Contactuspages");
                });

            modelBuilder.Entity("MyGymSystem.Models.Homepage", b =>
                {
                    b.Property<long>("Homepageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Homepageid"));

                    b.Property<string>("Featuredcontent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Lastupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sliderimagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Updatedbyadminid")
                        .HasColumnType("bigint");

                    b.Property<string>("Welcomemessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Homepageid");

                    b.HasIndex("Updatedbyadminid");

                    b.ToTable("Homepages");
                });

            modelBuilder.Entity("MyGymSystem.Models.Invoice", b =>
                {
                    b.Property<long>("Invoiceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Invoiceid"));

                    b.Property<decimal?>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Filepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Invoicedate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Memberid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Paymentid")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Invoiceid");

                    b.HasIndex("Memberid");

                    b.HasIndex("Paymentid")
                        .IsUnique()
                        .HasFilter("[Paymentid] IS NOT NULL");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("MyGymSystem.Models.Member", b =>
                {
                    b.Property<long>("Memberid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Memberid"));

                    b.Property<DateTime?>("Dateofbirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fitnessgoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Memberid");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MyGymSystem.Models.Membershipplan", b =>
                {
                    b.Property<long>("Planid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Planid"));

                    b.Property<long?>("Createdbyadminid")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durationmonths")
                        .HasColumnType("int");

                    b.Property<string>("Planname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plantype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Planid");

                    b.HasIndex("Createdbyadminid");

                    b.ToTable("Membershipplans");
                });

            modelBuilder.Entity("MyGymSystem.Models.Payment", b =>
                {
                    b.Property<long>("Paymentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Paymentid"));

                    b.Property<decimal>("Amountpaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Externaltransactionid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Paymentmethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paymentstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Paymentid");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyGymSystem.Models.Role", b =>
                {
                    b.Property<long>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Roleid"));

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Roleid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MyGymSystem.Models.Subscription", b =>
                {
                    b.Property<long>("Subscriptionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Subscriptionid"));

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Memberid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Paymentid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Planid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Subscriptionid");

                    b.HasIndex("Createdat");

                    b.HasIndex("Enddate");

                    b.HasIndex("Memberid");

                    b.HasIndex("Paymentid")
                        .IsUnique()
                        .HasFilter("[Paymentid] IS NOT NULL");

                    b.HasIndex("Planid");

                    b.HasIndex("Startdate");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MyGymSystem.Models.Testimonial", b =>
                {
                    b.Property<long>("Testimonialid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Testimonialid"));

                    b.Property<string>("Approvalstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Approvedbyadminid")
                        .HasColumnType("bigint");

                    b.Property<string>("Feedbacktext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Memberid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Submitteddate")
                        .HasColumnType("datetime2");

                    b.HasKey("Testimonialid");

                    b.HasIndex("Approvedbyadminid");

                    b.HasIndex("Memberid");

                    b.ToTable("Testimonials", t =>
                        {
                            t.HasCheckConstraint("CK_Testimonial_Approvalstatus", "Approvalstatus in ('Pending','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("MyGymSystem.Models.Trainer", b =>
                {
                    b.Property<long>("Trainerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Trainerid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Trainerid");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("MyGymSystem.Models.Userlogin", b =>
                {
                    b.Property<long>("Loginid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Loginid"));

                    b.Property<long?>("Adminid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Memberid")
                        .HasColumnType("bigint");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Roleid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Trainerid")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Loginid");

                    b.HasIndex("Adminid");

                    b.HasIndex("Memberid");

                    b.HasIndex("Roleid");

                    b.HasIndex("Trainerid");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Userlogins");
                });

            modelBuilder.Entity("MyGymSystem.Models.Workoutplan", b =>
                {
                    b.Property<long>("Workoutplanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Workoutplanid"));

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Memberid")
                        .HasColumnType("bigint");

                    b.Property<string>("Plandescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Routinedetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<long?>("Trainerid")
                        .HasColumnType("bigint");

                    b.HasKey("Workoutplanid");

                    b.HasIndex("Memberid");

                    b.HasIndex("Trainerid");

                    b.ToTable("Workoutplans");
                });

            modelBuilder.Entity("MyGymSystem.Models.Aboutuspage", b =>
                {
                    b.HasOne("MyGymSystem.Models.Admin", "Updatedbyadmin")
                        .WithMany("Aboutuspages")
                        .HasForeignKey("Updatedbyadminid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Updatedbyadmin");
                });

            modelBuilder.Entity("MyGymSystem.Models.Contactuspage", b =>
                {
                    b.HasOne("MyGymSystem.Models.Admin", "Updatedbyadmin")
                        .WithMany("Contactuspages")
                        .HasForeignKey("Updatedbyadminid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Updatedbyadmin");
                });

            modelBuilder.Entity("MyGymSystem.Models.Homepage", b =>
                {
                    b.HasOne("MyGymSystem.Models.Admin", "Updatedbyadmin")
                        .WithMany("Homepages")
                        .HasForeignKey("Updatedbyadminid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Updatedbyadmin");
                });

            modelBuilder.Entity("MyGymSystem.Models.Invoice", b =>
                {
                    b.HasOne("MyGymSystem.Models.Member", "Member")
                        .WithMany("Invoices")
                        .HasForeignKey("Memberid");

                    b.HasOne("MyGymSystem.Models.Payment", "Payment")
                        .WithMany("Invoices")
                        .HasForeignKey("Paymentid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Member");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MyGymSystem.Models.Membershipplan", b =>
                {
                    b.HasOne("MyGymSystem.Models.Admin", "Createdbyadmin")
                        .WithMany("Membershipplans")
                        .HasForeignKey("Createdbyadminid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Createdbyadmin");
                });

            modelBuilder.Entity("MyGymSystem.Models.Subscription", b =>
                {
                    b.HasOne("MyGymSystem.Models.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Memberid");

                    b.HasOne("MyGymSystem.Models.Payment", "Payment")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Paymentid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyGymSystem.Models.Membershipplan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Planid");

                    b.Navigation("Member");

                    b.Navigation("Payment");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MyGymSystem.Models.Testimonial", b =>
                {
                    b.HasOne("MyGymSystem.Models.Admin", "Approvedbyadmin")
                        .WithMany("Testimonials")
                        .HasForeignKey("Approvedbyadminid");

                    b.HasOne("MyGymSystem.Models.Member", "Member")
                        .WithMany("Testimonials")
                        .HasForeignKey("Memberid");

                    b.Navigation("Approvedbyadmin");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyGymSystem.Models.Userlogin", b =>
                {
                    b.HasOne("MyGymSystem.Models.Admin", "Admin")
                        .WithMany("Userlogins")
                        .HasForeignKey("Adminid");

                    b.HasOne("MyGymSystem.Models.Member", "Member")
                        .WithMany("Userlogins")
                        .HasForeignKey("Memberid");

                    b.HasOne("MyGymSystem.Models.Role", "Role")
                        .WithMany("Userlogins")
                        .HasForeignKey("Roleid");

                    b.HasOne("MyGymSystem.Models.Trainer", "Trainer")
                        .WithMany("Userlogins")
                        .HasForeignKey("Trainerid");

                    b.Navigation("Admin");

                    b.Navigation("Member");

                    b.Navigation("Role");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MyGymSystem.Models.Workoutplan", b =>
                {
                    b.HasOne("MyGymSystem.Models.Member", "Member")
                        .WithMany("Workoutplans")
                        .HasForeignKey("Memberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyGymSystem.Models.Trainer", "Trainer")
                        .WithMany("Workoutplans")
                        .HasForeignKey("Trainerid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MyGymSystem.Models.Admin", b =>
                {
                    b.Navigation("Aboutuspages");

                    b.Navigation("Contactuspages");

                    b.Navigation("Homepages");

                    b.Navigation("Membershipplans");

                    b.Navigation("Testimonials");

                    b.Navigation("Userlogins");
                });

            modelBuilder.Entity("MyGymSystem.Models.Member", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Subscriptions");

                    b.Navigation("Testimonials");

                    b.Navigation("Userlogins");

                    b.Navigation("Workoutplans");
                });

            modelBuilder.Entity("MyGymSystem.Models.Membershipplan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MyGymSystem.Models.Payment", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MyGymSystem.Models.Role", b =>
                {
                    b.Navigation("Userlogins");
                });

            modelBuilder.Entity("MyGymSystem.Models.Trainer", b =>
                {
                    b.Navigation("Userlogins");

                    b.Navigation("Workoutplans");
                });
#pragma warning restore 612, 618
        }
    }
}
